# Generated by Django 6.0 on 2025-12-16 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('birth_date', models.DateField(verbose_name='জন্ম তারিখ')),
                ('birth_certificate_no', models.CharField(max_length=50, verbose_name='জন্ম নিবন্ধন নম্বর')),
                ('gender', models.CharField(choices=[('Male', 'পুরুষ'), ('Female', 'মহিলা')], max_length=10, verbose_name='লিঙ্গ')),
                ('father_name', models.CharField(max_length=100, verbose_name='পিতার নাম')),
                ('mother_name', models.CharField(max_length=100, verbose_name='মাতার নাম')),
                ('guardian_name', models.CharField(max_length=100, verbose_name='অভিভাবকের নাম')),
                ('mobile', models.CharField(max_length=15, verbose_name='মোবাইল')),
                ('admission_class', models.CharField(max_length=20, verbose_name='ভর্তি শ্রেণি')),
                ('previous_class', models.CharField(blank=True, max_length=20, null=True, verbose_name='পূর্ববর্তী শ্রেণি')),
                ('previous_institute', models.CharField(blank=True, max_length=200, null=True, verbose_name='পূর্ববর্তী প্রতিষ্ঠান')),
                ('status', models.CharField(choices=[('PENDING', 'Payment Pending'), ('ACCEPTED', 'Accepted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10, verbose_name='অবস্থা')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরি তারিখ')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkash_trxid', models.CharField(max_length=50, verbose_name='bKash TrxID')),
                ('bkash_number', models.CharField(max_length=20, verbose_name='bKash Number')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('verified', models.BooleanField(default=False, verbose_name='যাচাই হয়েছে')),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.admission', verbose_name='ভর্তি')),
            ],
        ),
    ]
